const projectsData = [
  {
    titleKey: "projects.portfolioNext",
    imgSrc: "/images/project/portNext.png",
    altKey: "projects.portfolioNextAlt",
    tags: "Next.js, Tailwind, Framer Motion, TypeScript, i18n",
    id: "portfolio-next",
    siteLink: "https://portfolio-dev-green.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Portfolio_next",
    descKey: "projects.portfolioNextDesc",
  },
  {
    titleKey: "projects.techzoow",
    imgSrc: "/images/project/TechZoow.png",
    altKey: "projects.techzoow",
    tags: "React, Tailwind, JavaScript, CSS, HTML",
    id: "techzoow",
    siteLink: "https://www.techzoow.com.br/",
    githubLink: "",
    descKey: "projects.techzoowDesc",
  },
  {
    titleKey: "projects.portfolio",
    imgSrc: "/images/project/portReact.png",
    altKey: "projects.portfolioAlt",
    tags: "React, Tailwind, TypeScript, i18n",
    id: "portfolio",
    siteLink: "https://portfolio-moniquead.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Portfolio_2025.git",
    descKey: "projects.portfolioDesc",
  },
  {
    titleKey: "projects.aura",
    imgSrc: "/images/project/aura.jpeg",
    altKey: "projects.auraAlt",
    tags: "Ionic, React, Firebase, TypeScript, Capacitor, Vite",
    id: "aura",
    siteLink: "",
    githubLink: "https://github.com/Monique-Duarte/Aura",
    descKey: "projects.auraDesc",
  },
  {
    titleKey: "projects.disneyCopy",
    imgSrc: "/images/project/disney.png",
    altKey: "projects.disneyCopyAlt",
    tags: "Css, JavaScripts, Gulp",
    id: "disney-copy",
    siteLink: "https://clone-disney-plus-nine-liard.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Clone_DisneyPlus.git",
    descKey: "projects.disneyCopyDesc",
  },
  {
    titleKey: "projects.movieLandingPage",
    imgSrc: "/images/project/dragon.jpeg",
    altKey: "projects.movieLandingPageAlt",
    tags: "Css, JavaScripts, Gulp",
    id: "movie-landing-page",
    siteLink: "https://como-treinar-o-seu-dragao.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Como_Treinar_o_Seu_Dragao.git",
    descKey: "projects.movieLandingPageDesc",
  },
  {
    titleKey: "projects.hemaToma",
    imgSrc: "/images/project/game.jpg",
    altKey: "projects.hemaTomaAlt",
    tags: "bootstrap, JavaScript, CSS",
    id: "hema-toma",
    siteLink: "https://game-hema-toma.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Game-Hema-Toma.git",
    descKey: "projects.hemaTomaDesc",
  },
  {
    titleKey: "projects.restaurant",
    imgSrc: "/images/project/restaurante.jpg",
    altKey: "projects.restaurantAlt",
    tags: "JavaScript, HTML, CSS, Bootstrap",
    id: "restaurant",
    siteLink: "https://page-restaurante-alpha.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto-3-Page-Restaurante.git",
    descKey: "projects.restaurantDesc",
  },
  {
    titleKey: "projects.stopwatch",
    imgSrc: "/images/project/cronometro.jpg",
    altKey: "projects.stopwatchAlt",
    tags: "JavaScript, CSS, HTML, SCSS",
    id: "stopwatch",
    siteLink: "https://cronometro-zeta-ebon.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Tarefas-Cronometro",
    descKey: "projects.stopwatchDesc",
  },
  {
    titleKey: "projects.allfood",
    imgSrc: "/images/project/allfood.jpg",
    altKey: "projects.allfoodAlt",
    tags: "JavaScript, TypeScript, API, Python, Docker, Node.js",
    id: "allfood",
    siteLink: " ",
    githubLink: "https://github.com/Monique-Duarte/AllFood",
    descKey: "projects.allfoodDesc",
  },
  {
    titleKey: "projects.phoneBook",
    imgSrc: "/images/project/lista.png",
    altKey: "projects.phoneBookAlt",
    tags: "AngularJS, CSS, Bootstrap",
    id: "phone-book",
    siteLink: "https://lista-telefonica-omega.vercel.app/",
    githubLink: "https://lista-telefonica-mu.vercel.app/",
    descKey: "projects.phoneBookDesc",
  },
  {
    titleKey: "projects.randomizer",
    imgSrc: "/images/project/sorteador.jpg",
    altKey: "projects.randomizerAlt",
    tags: "Grunt, JavaScript, HTML, CSS",
    id: "randomizer",
    siteLink: "https://sorteador-ten-eosin.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Sorteador_Grunt",
  },
  {
    titleKey: "projects.spotifyClone",
    imgSrc: "/images/project/spotify.jpg",
    altKey: "projects.spotifyCloneAlt",
    tags: "JavaScript, HTML, CSS",
    id: "spotify-clone",
    siteLink: " ",
    githubLink: "https://github.com/Monique-Duarte/Projeto-Hashtag-Spotify",
    descKey: "projects.spotifyCloneDesc",
  },
  {
    titleKey: "projects.portfolioLess",
    imgSrc: "/images/project/portless.png",
    altKey: "projects.portfolioLessAlt",
    tags: "Tailwind CSS, i18n",
    id: "portfolio-less",
    siteLink: "https://portfolio-less-seven.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/portfolio-less",
    descKey: "projects.portfolioLessDesc",
  },
  {
    titleKey: "projects.newsBlog",
    imgSrc: "/images/project/image.png",
    altKey: "projects.newsBlogAlt",
    tags: "HTML, CSS",
    id: "news-blog",
    siteLink: "https://projeto-blog-noticias.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto-blog-noticias.git",
  },
  {
    titleKey: "projects.nekoShop",
    imgSrc: "/images/project/logo.png",
    altKey: "projects.nekoShopAlt",
    tags: "HTML, CSS",
    id: "neko-shop",
    siteLink: "https://neko-shop.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Neko-Shop-origin.git",
  },
  {
    titleKey: "projects.gameShop",
    imgSrc: "/images/project/gif_mario2.gif",
    altKey: "projects.gameShopAlt",
    tags: "HTML, CSS",
    id: "game-shop",
    siteLink: "https://site-game-shop-ten-coral.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Site-Game-Shop.git",
  },
  {
    titleKey: "projects.newsPortal",
    imgSrc: "/images/project/image.png",
    altKey: "projects.newsPortalAlt",
    tags: "HTML, CSS",
    id: "news-portal",
    siteLink: "https://meu-portal-mu.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Portal-de-Noticias.git",
  },
  {
    titleKey: "projects.form",
    imgSrc: "/images/project/form.png",
    altKey: "projects.formAlt",
    tags: "HTML, CSS, JavaScript",
    id: "form",
    siteLink: "https://formulario-js-plum.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Formulario_JS.git",
  },
  {
    titleKey: "projects.photoGallery",
    imgSrc: "/images/project/camera.png",
    altKey: "projects.photoGalleryAlt",
    tags: "HTML, CSS, JavaScript",
    id: "photo-gallery",
    siteLink: "https://galeria-de-fotos-cyan.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Galeria-de-Fotos.git",
  },
  {
    titleKey: "projects.ebacMotors",
    imgSrc: "/images/project/carro.svg",
    altKey: "projects.ebacMotorsAlt",
    tags: "HTML, CSS",
    id: "ebac-motors",
    siteLink: "https://ebac-motors-six-alpha.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Ebac-Motors.git",
  },
  {
    titleKey: "projects.salesAd",
    imgSrc: "/images/project/994737.png",
    altKey: "projects.salesAdAlt",
    tags: "projects.salesAdTags",
    id: "sales-ad",
    siteLink: "https://anuncio-jquery.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/formulario-plugs-jquery.git",
  },
  {
    titleKey: "projects.portalNewsGrid",
    imgSrc: "/images/project/image.png",
    altKey: "projects.portalNewsGridAlt",
    tags: "HTML, CSS",
    id: "portal-news-grid",
    siteLink: "https://portal-de-noticias-grid.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Ebac_News.git",
  },
  {
    titleKey: "projects.agenda",
    imgSrc: "/images/project/pngwing.com.png",
    altKey: "projects.agendaAlt",
    tags: "HTML, CSS",
    id: "agenda",
    siteLink: "https://projeto-agendaonline.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto_Agenda.git",
  },
  {
    titleKey: "projects.gradeSystem",
    imgSrc: "/images/project/calculadora.png",
    altKey: "projects.gradeSystemAlt",
    tags: "HTML, CSS",
    id: "grade-system",
    siteLink: "https://monique-projeto-calculadora-medias.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto_Calculadora_Medias.git",
  },
  {
    titleKey: "projects.todoList",
    imgSrc: "/images/project/form.png",
    altKey: "projects.todoListAlt",
    tags: "HTML, CSS",
    id: "todo-list",
    siteLink: "https://lista-de-tarefas-jquery-opal.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Lista-de-tarefas_jquery.git",
  },
];

export default projectsData;